name: Build and deploy ASP.Net Core app to Azure Web App - BadgerClanApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build BadgerClanAPI
        run: dotnet build ./BadgerClanAPI/BadgerClanAPI.csproj --configuration Release

      - name: Publish BadgerClanAPI
        run: dotnet publish ./BadgerClanAPI/BadgerClanAPI.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      # Exclude conflicting config files by manually removing them
      - name: Remove conflicting config files from Client
        run: |
          rm -f "${{env.DOTNET_ROOT}}/myapp/BadgerClan.Client/appsettings.json"
          rm -f "${{env.DOTNET_ROOT}}/myapp/BadgerClan.Client/appsettings.Development.json"

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BadgerClanApi'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
