name: Build and deploy ASP.Net Core app to Azure Web App - BadgerClanApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build and publish the app
        run: |
          cd ./BadgerClanAPI
          dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A981676BFC5E46519C8BE0D23297F66C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E9E30F6621284CBD9C060F49F05A0CEB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8FC318A09AC451E8CCDD513EA19AADD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BadgerClanApi'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
